name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    name: JS Linting

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3.2.1
        name: Cache dependencies
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}

      - name: Prepare the project
        run: |
          cp .env.example .env
          npm ci

      - name: Run linter
        run: |
          npm run lint
